name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create and publish a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node (npm registry)
        uses: actions/setup-node@v2-beta
        with:
          node-version: "15"
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Generate changelog
        uses: scottbrenner/generate-changelog-action@v1
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup Node (GitHub registry)
        uses: actions/setup-node@v2-beta
        with:
          node-version: "15"
          registry-url: https://npm.pkg.github.com
      - name: Change package name
        uses: datamonsters/replace-action@v2
        with:
          files: package.json
          replacements: '"universal-geocoder"="@universal-geocoder/universal-geocoder"'
      - name: Publish to GitHub
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
