name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create and publish a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set output vars
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/}
      - name: Setup Node (npm registry)
        uses: actions/setup-node@v2
        with:
          node-version: "15"
          registry-url: https://registry.npmjs.org
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Generate changelog
        uses: scottbrenner/generate-changelog-action@v1.3.3
        id: changelog
        env:
          REPO: ${{ github.repository }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: Release ${{ steps.vars.outputs.tag }}
          body: |
            ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Setup Node (GitHub registry)
        uses: actions/setup-node@v2
        with:
          node-version: "15"
          registry-url: https://npm.pkg.github.com
      - name: Change package name
        uses: datamonsters/replace-action@v2
        with:
          files: package.json
          replacements: '"universal-geocoder"="@universal-geocoder/universal-geocoder"'
      - name: Publish to GitHub
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
